const express = require('express');
const adminRouter = express.Router();
const adminRouterController = require('../controller/adminController');

adminRouter.get('/adminpaneldashboard', adminRouterController.getAdminPanelDashboard);
adminRouter.get('/adminBet', adminRouterController.getAdminBetPage);
adminRouter.get('/declareMatka', adminRouterController.getDeclareData);
adminRouter.post('/declareSingle', adminRouterController.postDeclareSingleResult);
adminRouter.post('/declarePatti', adminRouterController.postDeclarePattiResult);
adminRouter.get('/userDownLine', adminRouterController.getUserDownLine);
adminRouter.post('/admincreateuser', adminRouterController.postAdmincreateuser);
adminRouter.post('/postTransaction', adminRouterController.postTransaction);
adminRouter.get('/userProfile/:userId', adminRouterController.getUserProfieByAdmin);
adminRouter.post('/resetpasswordnotcheckoldpassword', adminRouterController.adminChangePasswordofUser);
adminRouter.get("/adminseepersonallyuserbethistory/:userId", adminRouterController.adminSeeUserPersonallyBetHistory);
adminRouter.get('/accountsettlement/:userId', adminRouterController.getAccountSettlement);
adminRouter.get('/adminaccountsettlement', adminRouterController.getAdminAccountStatement);
adminRouter.get('/masterpanelbyadmindashboard', adminRouterController.getMasterDownlineList);
adminRouter.post('/admincreatemaster', adminRouterController.postAdmincreatemaster);
adminRouter.post('/postTransactionofmaster', adminRouterController.postTransactionofmaster);
adminRouter.get('/adminseemasterprofile/:userId', adminRouterController.getAdminSeeMasterProfile);
adminRouter.get('/accountstatementofmaster/:userId', adminRouterController.getAdminSeeMasterAccountStatement);
adminRouter.post('/resetpasswordnotcheckoldpasswordofmaster', adminRouterController.adminChangePasswordofMaster);
// adminRouter.get('/agentpanelbyadmindashboard', adminRouterController.getAgentPanelDashboard);
module.exports = adminRouter;